# version: 1.0
AWSTemplateFormatVersion: 2010-09-09
Description: >
  This Template Deploys Basic AWS IAM role for S3 service.
Parameters:
  s3ReadBucketAccess:
    Type: String
    Description: Comma delimited list of s3 buckets (no space after the comma) that the IAM role will need Read access to. Bucket ARN required. Optional value to fill.
  s3WriteBucketAccess:
    Type: String
    Description: Comma delimited list of s3 buckets (no space after the comma) that the IAM role will need Write access to. Bucket ARN required. Optional value to fill.
  KMSKeys:
    Type: String
    Description: Comma delmited list of all encryption keys (no space after the comma) that the IAM role will need encrypt/decrypt access to. ARN required. Optional value to fill.
  IAMRolename:
    Type: String
    Description: Name of the IAM role

Conditions:
  S3WriteBucketAccessProvided: !Not [!Equals [!Ref s3WriteBucketAccess, ""]]
  S3ReadBucketAccessProvided: !Not [!Equals [!Ref s3ReadBucketAccess, ""]]
  KMSKeysProvided: !Not [!Equals [!Ref KMSKeys, ""]]

Resources:
  S3IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref IAMRolename
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              - arn:aws:iam::<accountid>:root
              # you can limit it further down to the role name itself
            #  - arn:aws:iam::<accountid>:role/<s3_role_name> 
          Action:
          - sts:AssumeRole
      Path: "/"

  S3AccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    DependsOn: S3IAMRole
    Properties:
      Users:
        - !Ref IAMRolename
      ManagedPolicyName: !Sub "${IAMRolename}_access_policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - !If
            - S3ReadBucketAccessProvided
            - Sid: "S3ReadAccess"
              Effect: "Allow"
              Action:
                - "s3:ListBucket*"
                - "s3:ListObject*"
                - "s3:GetBucket*"
                - "s3:GetObject*"
                - "s3:ListMultipartUploadParts"
              Resource: !Split
                - ","
                - !Ref s3ReadBucketAccess
            - !Ref "AWS::NoValue"

          - !If
            - S3WriteBucketAccessProvided
            - Sid: "S3WriteAccess"
              Effect: "Allow"
              Action:
                - "s3:PutAnalyticsConfiguration"
                - "s3:AbortMultipartUpload"
                - "s3:PutBucketVersioning"
                - "s3:PutLifecycleConfiguration"
                - "s3:PutInventoryConfiguration"
                - "s3:DeleteObjectVersion"
                - "s3:RestoreObject"
                - "s3:DeleteObject"
                - "s3:DeleteObjectTagging"
                - "s3:PutObjectVersionTagging"
                - "s3:DeleteObjectVersionTagging"
                - "s3:PutObject*"
                - "s3:PutBucketNotification"
              Resource: !Split
                - ","
                - !Ref s3WriteBucketAccess
            - !Ref "AWS::NoValue"
                            
          - !If
            - KMSKeysProvided
            - Sid: "KMSKeysAccess"
              Effect: "Allow"
              Action:
                - "kms:Decrypt"
                - "kms:Encrypt"
                - "kms:DescribeKey"
                - "kms:ReEncrypt*"
                - "kms:GenerateDataKey*"
                - "kms:RevokeGrant"
                - "kms:ListGrants"
                - "kms:CreateGrant"
              Resource: !Split
                - ","
                - !Ref KMSKeys
            - !Ref "AWS::NoValue"
          - Effect: "Allow"
            Action:
              - s3:ListAllMyBuckets
              - s3:HeadBucket
            Resource: "*"
            Condition:
              Bool:
                aws:SecureTransport:
                  - True
          - Effect: "Allow"
            Action:
              - "kms:ListAliases"
            Resource: "*"
            Condition:
              Bool:
                aws:SecureTransport:
                  - True